---
- name: Install jedi-vim vim plugin (via pathogen)
  git:
    repo=https://github.com/davidhalter/jedi-vim.git
    dest={{ home }}/.vim/bundle/jedi-vim
    version=HEAD
    recursive=no
- name: Check out jedi manually into jedi-vim/jedi
  git:
    repo=https://github.com/davidhalter/jedi.git
    dest={{ home }}/.vim/bundle/jedi-vim/jedi
    version=HEAD
- name: Create folder ~/.vim/bundle-last
  file:
    dest={{ home }}/.vim/bundle-last
    state=directory
- name: Install vim-pyenv vim plugin (via pathogen)
  git:
    repo=https://github.com/lambdalisue/vim-pyenv.git
    dest={{ home }}/.vim/bundle-last/vim-pyenv

